### ISSUE TITLE
Update footer to match anaconda.org

### ISSUE THREAD

**Issue by mistakevin** [Anaconda-Server/docs.anaconda.org#219]
<img width="1221" alt="screen shot 2015-12-03 at 8 38 33 am" src="https://cloud.githubusercontent.com/assets/4411115/11563382/43a2fba4-9999-11e5-9fe7-d735ae6dbcae.png">

**Comment by mistakevin** [comment]
Old Bootstrap Footer from anaconda-server
```html
<footer>
  <div class="row">
    <div class="col-md-3 col-md-offset-3">
      <h4><strong>Anaconda Cloud</strong></h4>
      <p>
        <a href="{{url_for('misc.about')}}">About</a><br>
        <a href="{{url_for('misc.pricing')}}">Pricing</a><br>
        <a href="http://docs.anaconda.org" target="_blank">Documentation</a><br>
        <a href="{{url_for('misc.contact')}}">Support</a><br>
        <a href="https://www.continuum.io/our-story" target="_blank">About Continuum</a><br>
        <a href="http://continuum.io/downloads" target="_blank">Download Anaconda</a><br>
        <span>{{settings.BRAND}} v{{binstar_version}}</span>
      </p>
    </div>
    <div class="col-md-3">
      <h4><strong>Community</strong></h4>
      <p>
        <a href="https://www.continuum.io/content/anaconda-community" target="_blank">Anaconda Community</a><br>
        <a href="https://www.continuum.io/open-source-core-modern-software" target="_blank">Open Source</a><br>
        <a href="https://www.continuum.io/content/numfocus" target="_blank">NumFOCUS</a><br>
        <a href="https://www.continuum.io/content/why-python" target="_blank">Why Python</a><br>
        <a href="https://www.continuum.io/support" target="_blank">Support</a><br>
        <a href="https://www.continuum.io/blog/developer-blog" target="_blank">Developer Blog</a><br>
        <a href="https://www.continuum.io/snapshot-our-contributors" target="_blank">Our Contributors</a>
      </p>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-12">
      <ul>
        <li><a href="https://twitter.com/ContinuumIO" target="_blank"><i class="fa fa-2x fa-twitter"></i></a></li>
        <li><a href="https://www.facebook.com/ContinuumAnalytics" target="_blank"><i class="fa fa-2x fa-facebook"></i></a></li>
        <li><a href="http://www.slideshare.net/continuumio" target="_blank"><i class="fa fa-2x fa-slideshare"></i></a></li>
        <li><a href="https://www.linkedin.com/company/continuum-analytics-inc-" target="_blank"><i class="fa fa-2x fa-linkedin"></i></a></li>
        <li><a href="https://instagram.com/continuumanalytics/" target="_blank"><i class="fa fa-2x fa-instagram"></i></a></li>
        <li><a href="https://www.youtube.com/c/ContinuumIo" target="_blank"><i class="fa fa-2x fa-youtube"></i></a></li>
        <li><a href="https://github.com/ContinuumIO" target="_blank"><i class="fa fa-2x fa-github"></i></a></li>
      </ul>
    </div>
  </div>
</footer>
<div class="license">
  <div class="row">
    <div class="col-md-12 text-center">
      <h5>
        <a href="https://www.continuum.io/privacy-policy" target="_blank">PRIVACY POLICY</a>
        &nbsp;&#124;&nbsp;
        <a href="https://www.continuum.io/anaconda-end-user-license-agreement" target="_blank">EULA</a>
        &nbsp; &nbsp; &nbsp; &copy;
        2015 Continuum Analytics, Inc. All Rights Reserved.
      </h5>
    </div>
  </div>
</div>

```

Relevant LESS from anaconda-server
```less
@footer-height: 315px;

footer {
  background-color: #253746;
  color: white;
  padding: 16px;
  a, span {
    color: #EFEFEF;
    font-weight: 100;
  }
  a:hover, a:active {
    color: #CCCCCC;
  }
  h4 {
    color: #EFEFEF;
    font-weight: 700;
  }
  ul {
    list-style-type: none;
    text-align: center;
    margin-left: 0;
    padding-left: 0;
    li {
      display: inline-block;
      margin-left: 30px;
      margin-right: 30px;
    }
  }

  p {
    line-height: 1.75;
  }
}

.license {
  padding: 0.75rem;
  background-color: #15202b;
  h5, a {
    color: #5C6771;
    font-weight: 100;
    font-family: 'Lato';
  }
}

footer, .push {
  min-height: @footer-height; /* '.push' must be the same height as 'footer' */
}
```
