### ISSUE TITLE
Building an Anaconda Navigator App

### ISSUE THREAD

**Issue by tensionhead** [Anaconda-Server/docs.anaconda.org#278]
Hi,

I want to build an Anaconda Navigator app using a PyQt5 program. I am trying to follow the steps here:

https://docs.anaconda.com/anaconda/navigator/tutorials/nav-app/

But a few things seem to be missing in this doc, especially in the **Entry key** section:
![Screenshot from 2020-04-23 11:47:01](https://user-images.githubusercontent.com/10595420/80085657-d37ca900-8558-11ea-85ef-370d1f284f1c.png)

Would be great to have more info here, Anaconda Apps could be a really nice thing for deployment!

**Comment by tensionhead** [comment]
Actually, by inspecting the recipe of ```qtconsole```, I just added these lines to my ```meta.yaml```:
```
app:
    entry: myapp
    summary: some text shown in the Navigator
    type: desk
```

After conda-build and a local install on osx, the Navigator indeed sported my click-launchable app :)
So I didn't even need a ```build.sh``` in the end. Not sure if it works on Windows atm, is there more information somewhere about Navigator Apps?

**Comment by tensionhead** [comment]
So something I can't get to work is that my icon shows in the Navigator. I put

```
app:
    entry: myapp
    summary: some text shown in the Navigator
    type: desk
    icon: myapp_logo
```
and this is also recognized by conda-build (the logo has to be in the recipe), however it's not shown in the Navigator. All other apps (e.g. Jupyter or Spyder) have these ```icon:``` entries and a ```.png``` inside their ```/recipe```, can't figure out why it works for them but not for my app.
